### ISSUE TITLE
Build error on Ubuntu 20.04

### ISSUE THREAD

**Issue by wintervaler** [rigaya/QSVEnc#39]
Hi there! I am trying to build QSVEnc on Ubuntu 20.04. I have a working QSV/Intel Media environment in `ffmpeg` and other programs. I am running into the following output when I run the `make` command as suggested in the Build help:

```
/usr/bin/ld: plugin_subburn.cpp:(.text+0xc56): undefined reference to `ProcessorSubBurnD3DAVX::ProcessorSubBurnD3DAVX()'
/usr/bin/ld: plugin_subburn.cpp:(.text+0xc6b): undefined reference to `ProcessorSubBurnAVX2::ProcessorSubBurnAVX2()'
/usr/bin/ld: plugin_subburn.cpp:(.text+0xe5c): undefined reference to `ProcessorSubBurnAVX::ProcessorSubBurnAVX()'
collect2: error: ld returned 1 exit status
make: *** [makefile:13: qsvencc] Error 1
```

Googling this issue reveals very little - is there a dependency I am missing or is something else the problem here? I've attached my full `make` output. Thank you!

[QSVEnc Build Error.txt](https://github.com/rigaya/QSVEnc/files/5578370/QSVEnc.Build.Error.txt)

**Comment by rigaya** [comment]
I think I have found the problem, the build on a system without AVX/AVX2 support had a problem and was causing your issue. I've fixed the build on [QSVEnc 4.11](https://github.com/rigaya/QSVEnc/releases/tag/4.11), hope it works now.

Please note that QSVEnc 4.11 changed the assembler from yasm to nasm (not related to this issue), so you might need to install nasm additionally for build.

**Comment by wintervaler** [comment]
Thank you very much for such a quick response! I'm going to test it out now.

**Comment by rigaya** [comment]
I'll close this issue, as the problem should have been fixed.
